"""
firebase_client.py
──────────────────
Handles all Firebase Realtime Database operations for ARIA.
Every read/write to the database goes through this file.
"""

import firebase_admin
from firebase_admin import credentials, db
from dotenv import load_dotenv
import os

load_dotenv()

# ── Initialize Firebase (only once) ──────────────────────────────────────────
def init_firebase():
    if not firebase_admin._apps:
        cred = credentials.Certificate(os.getenv("FIREBASE_CREDENTIALS_PATH"))
        firebase_admin.initialize_app(cred, {
            "databaseURL": os.getenv("FIREBASE_DATABASE_URL")
        })
        print("✅ Firebase connected")

init_firebase()

HOTEL_ID = os.getenv("HOTEL_ID", "hotel_grand_001")


# ══════════════════════════════════════════════════════════════════════════════
# STAFF OPERATIONS
# ══════════════════════════════════════════════════════════════════════════════

def get_all_staff() -> dict:
    """Returns all staff members for this hotel."""
    ref = db.reference(f"/hotels/{HOTEL_ID}/staff")
    return ref.get() or {}


def get_available_staff() -> list:
    """Returns only staff who are currently available (not assigned)."""
    all_staff = get_all_staff()
    available = []
    for staff_id, data in all_staff.items():
        if data.get("status") == "available":
            available.append({"id": staff_id, **data})
    return available


def update_staff_status(staff_id: str, status: str, assignment: str = None):
    """
    Updates a staff member's status.
    status options: 'available' | 'assigned' | 'offline'
    """
    ref = db.reference(f"/hotels/{HOTEL_ID}/staff/{staff_id}")
    update_data = {"status": status}
    if assignment:
        update_data["current_assignment"] = assignment
    else:
        update_data["current_assignment"] = None
    ref.update(update_data)


def update_staff_location(staff_id: str, location: str):
    """Called when staff checks in from a floor/location."""
    ref = db.reference(f"/hotels/{HOTEL_ID}/staff/{staff_id}")
    ref.update({"last_location": location})


# ══════════════════════════════════════════════════════════════════════════════
# GUEST OPERATIONS
# ══════════════════════════════════════════════════════════════════════════════

def get_guests_in_zone(floors: list) -> list:
    """Returns all guests currently on the specified floors."""
    ref = db.reference(f"/hotels/{HOTEL_ID}/guests")
    all_guests = ref.get() or {}
    affected = []
    for room, data in all_guests.items():
        if str(data.get("floor")) in [str(f) for f in floors]:
            affected.append({"room": room, **data})
    return affected


def update_guest_safety(room: str, status: str):
    """
    Updates guest safety status after they respond to alert.
    status options: 'safe' | 'needs_help' | 'unknown'
    """
    ref = db.reference(f"/hotels/{HOTEL_ID}/guests/{room}")
    ref.update({"safety_status": status})


def get_guest_by_room(room: str) -> dict:
    """Returns guest data for a specific room."""
    ref = db.reference(f"/hotels/{HOTEL_ID}/guests/{room}")
    return ref.get() or {}


def register_guest(room: str, name: str, phone: str, language: str, floor: int):
    """Called at hotel check-in. Registers guest in ARIA."""
    ref = db.reference(f"/hotels/{HOTEL_ID}/guests/{room}")
    ref.set({
        "name": name,
        "phone": phone,
        "language": language,        # e.g. "hi", "ja", "ar", "en"
        "floor": floor,
        "safety_status": "unknown",
        "alert_sent": False,
        "checked_in": True
    })


# ══════════════════════════════════════════════════════════════════════════════
# CRISIS OPERATIONS
# ══════════════════════════════════════════════════════════════════════════════

def create_crisis(crisis_data: dict) -> str:
    """
    Creates a new crisis record in Firebase.
    Returns the crisis_id generated by Firebase.
    """
    ref = db.reference(f"/hotels/{HOTEL_ID}/active_crises")
    new_crisis = ref.push(crisis_data)
    return new_crisis.key


def get_active_crises() -> dict:
    """Returns all currently active crises."""
    ref = db.reference(f"/hotels/{HOTEL_ID}/active_crises")
    return ref.get() or {}


def update_crisis(crisis_id: str, data: dict):
    """Updates a crisis record — used for status changes, adding assignments."""
    ref = db.reference(f"/hotels/{HOTEL_ID}/active_crises/{crisis_id}")
    ref.update(data)


def close_crisis(crisis_id: str):
    """
    Moves crisis from active_crises to crisis_history.
    Called when manager marks crisis as resolved.
    """
    # Get current crisis data
    crisis_ref = db.reference(f"/hotels/{HOTEL_ID}/active_crises/{crisis_id}")
    crisis_data = crisis_ref.get()

    if crisis_data:
        crisis_data["status"] = "resolved"

        # Move to history
        history_ref = db.reference(f"/hotels/{HOTEL_ID}/crisis_history/{crisis_id}")
        history_ref.set(crisis_data)

        # Remove from active
        crisis_ref.delete()


def add_crisis_timeline_event(crisis_id: str, event: str, actor: str):
    """
    Adds a timestamped event to the crisis timeline.
    Every action (staff dispatched, guest marked safe) is logged here.
    """
    import time
    ref = db.reference(f"/hotels/{HOTEL_ID}/active_crises/{crisis_id}/timeline")
    ref.push({
        "event": event,
        "actor": actor,
        "timestamp": int(time.time())
    })


# ══════════════════════════════════════════════════════════════════════════════
# DEMO DATA LOADER
# ══════════════════════════════════════════════════════════════════════════════

def load_demo_data():
    """
    Loads realistic demo data into Firebase.
    Run this once before your demo to populate the database.
    """
    hotel_ref = db.reference(f"/hotels/{HOTEL_ID}")

    # Hotel info
    hotel_ref.child("info").set({
        "name": "Hotel Grand",
        "address": "MG Road, Ludhiana, Punjab",
        "floors": 8,
        "total_rooms": 80
    })

    # Staff members
    hotel_ref.child("staff").set({
        "staff_001": {
            "name": "Rajesh Kumar",
            "role": "security",
            "phone": "+91XXXXXXXXXX",   # replace with real demo number
            "floor": 4,
            "last_location": "Floor 4 Corridor",
            "status": "available",
            "current_assignment": None
        },
        "staff_002": {
            "name": "Priya Sharma",
            "role": "nurse",
            "phone": "+91XXXXXXXXXX",   # replace with real demo number
            "floor": 1,
            "last_location": "Reception",
            "status": "available",
            "current_assignment": None
        },
        "staff_003": {
            "name": "Amit Singh",
            "role": "manager",
            "phone": "+91XXXXXXXXXX",   # replace with real demo number
            "floor": 1,
            "last_location": "Manager Office",
            "status": "available",
            "current_assignment": None
        },
        "staff_004": {
            "name": "Suresh Verma",
            "role": "housekeeping",
            "phone": "+91XXXXXXXXXX",
            "floor": 3,
            "last_location": "Floor 3",
            "status": "available",
            "current_assignment": None
        },
        "staff_005": {
            "name": "Deepak Rao",
            "role": "housekeeping",
            "phone": "+91XXXXXXXXXX",
            "floor": 5,
            "last_location": "Floor 5",
            "status": "available",
            "current_assignment": None
        }
    })

    # Guests across different floors with different languages
    hotel_ref.child("guests").set({
        "room_401": {"name": "Arjun Mehta",     "phone": "+91XXXXXXXXXX", "language": "hi", "floor": 4, "safety_status": "unknown", "alert_sent": False},
        "room_402": {"name": "Yuki Tanaka",     "phone": "+91XXXXXXXXXX", "language": "ja", "floor": 4, "safety_status": "unknown", "alert_sent": False},
        "room_403": {"name": "Ahmed Al-Rashid", "phone": "+91XXXXXXXXXX", "language": "ar", "floor": 4, "safety_status": "unknown", "alert_sent": False},
        "room_404": {"name": "Marie Dubois",    "phone": "+91XXXXXXXXXX", "language": "fr", "floor": 4, "safety_status": "unknown", "alert_sent": False},
        "room_412": {"name": "John Smith",      "phone": "+91XXXXXXXXXX", "language": "en", "floor": 4, "safety_status": "unknown", "alert_sent": False},
        "room_301": {"name": "Priya Nair",      "phone": "+91XXXXXXXXXX", "language": "hi", "floor": 3, "safety_status": "unknown", "alert_sent": False},
        "room_501": {"name": "Carlos Ruiz",     "phone": "+91XXXXXXXXXX", "language": "es", "floor": 5, "safety_status": "unknown", "alert_sent": False},
    })

    print("✅ Demo data loaded successfully")


if __name__ == "__main__":
    load_demo_data()
